spring.application.name=notification-service

server.port=9040
server.servlet.context-path=/notifications

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/notificationdb
spring.datasource.username=postgres
spring.datasource.password=Ivinjain@0099
spring.jpa.hibernate.ddl-auto=create-drop

eureka.client.service-url.defaultZone= http://localhost:8761/eureka