spring.application.name: api-gateway

server.port: 8080
eureka.client.service-url.defaultZone: http://localhost:8761/eureka

jwt.secretKey: je8r9ggha8whehr8ghahwes9we9hag0hwn09vna0w

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2

            - id: post-service
              uri: lb://POSTS-SERVICE
              predicates:
                - Path=/api/v1/posts/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter

            - id: connection-service
              uri: lb://CONNECTION-SERVICE
              predicates:
                - Path=/api/v1/connections/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter




#removes the docker instance from eureka server ****imp****
eureka.instance.prefer-ip-address: true
spring.cloud.inetutils.preferred-networks: 192.168



