spring.application.name=connection-service

server.port=9030
server.servlet.context-path=/connections

spring.neo4j.uri=neo4j+s://023bed1f.databases.neo4j.io
spring.neo4j.authentication.username=023bed1f
spring.neo4j.authentication.password=kx-ji93G1fubuY1Dqh-M-nv-r-wSlrAxGYLcDfuhlho

eureka.client.service-url.defaultZone=http://localhost:8761/eureka