spring.application.name=connection-service

server.port=9030
server.servlet.context-path=/api/v1/connections

spring.neo4j.uri=neo4j+s://507b3080.databases.neo4j.io
spring.neo4j.authentication.username=507b3080
spring.neo4j.authentication.password=JAGLS8orTEq-hYbo49toFiFU6qb2vn8X9d3Wq1Wsh6w
