spring.application.name=user-service
server.port=9020
server.servlet.context-path=/users

jwt.secretKey = je8r9ggha8whehr8ghahwes9we9hag0hwn09vna0w

spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=Ivinjain@0099
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone= http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true