spring.application.name=posts-service

server.port=9010

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postsDB
spring.datasource.username=postgres
spring.datasource.password=Ivinjain@0099
spring.jpa.hibernate.ddl-auto=update